@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user",
  "password": "123456",
  "chave-malvada": "não devia estar aqui"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/321